#!/usr/bin/python
import boto
import sys
import argparse

parser = argparse.ArgumentParser()

parser.add_argument('--profile', action='store', dest='profile', help='Specify the aws profile to use', required=True)
parser.add_argument('--serial', action='store', dest='serial', help='Serial Number or ARN of the MFA device', required=True)
parser.add_argument('--token', action='store', dest='token', help='MFA Token number', required=True)
parser.add_argument('--duration', action='store', dest='duration', help='MFA Token number', required=False)

results = parser.parse_args()


# if (len(sys.argv) <> 5):
#     print 'Usage ' + sys.argv[0] + ' access_key secret_key mfa_serial_number mfa_token'
#     exit(1)

# access_key = sys.argv[1]
# secret_key = sys.argv[2]
# mfa_serial_number = sys.argv[3]
# mfa_token = sys.argv[4]

if results.duration == "":
  tokenduration = 3600
else:
  tokenduration = results.duration

sts = boto.connect_sts(profile_name=results.profile)

token = sts.get_session_token(duration = tokenduration, force_new = True, mfa_serial_number = results.serial, mfa_token = results.token)
print 'export AWS_ACCESS_KEY=' + token.access_key
print 'export AWS_SECRET_KEY=' + token.secret_key
print 'export AWS_DELEGATION_TOKEN=' + token.session_token
